package com.datadrift.executor.change;

import com.datadrift.model.change.CreateIndexChange;
import com.datadrift.sql.dialect.SqlDialect;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CreateIndexExecutorTest {

    @Mock
    private JdbcTemplate jdbcTemplate;

    @Mock
    private SqlDialect sqlDialect;

    @Captor
    private ArgumentCaptor<String> sqlCaptor;

    private CreateIndexExecutor executor;

    @BeforeEach
    void setUp() {
        executor = new CreateIndexExecutor(jdbcTemplate, sqlDialect);
    }

    @Test
    void testExecute_SimpleIndex() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));
        String expectedSql = "CREATE INDEX \"idx_users_email\" ON \"users\" (\"email\")";

        // When
        executor.execute(change);

        // Then
        verify(jdbcTemplate).execute(expectedSql);
    }

    @Test
    void testGenerateSql_SimpleIndex() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertNotNull(sql);
        assertTrue(sql.contains("CREATE INDEX"));
        assertTrue(sql.contains("\"idx_users_email\""));
        assertTrue(sql.contains("\"users\""));
        assertTrue(sql.contains("\"email\""));
    }

    @Test
    void testGenerateSql_WithSchema() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setSchemaName("public");
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"public\".\"users\""));
    }

    @Test
    void testGenerateSql_UniqueIndex() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("uniq_users_username");
        change.setTableName("users");
        change.setColumns(List.of("username"));
        change.setUnique(true);

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("CREATE UNIQUE INDEX"));
    }

    @Test
    void testGenerateSql_MultipleColumns() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_name_email");
        change.setTableName("users");
        change.setColumns(List.of("name", "email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"name\", \"email\""));
    }

    @Test
    void testGenerateSql_AutoGeneratedIndexName_SingleColumn() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"idx_users_email\""));
    }

    @Test
    void testGenerateSql_AutoGeneratedIndexName_MultipleColumns() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setTableName("orders");
        change.setColumns(List.of("user_id", "created_at"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"idx_orders_user_id_created_at\""));
    }

    @Test
    void testGenerateSql_AutoGeneratedIndexName_UniqueIndex() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setTableName("users");
        change.setColumns(List.of("username"));
        change.setUnique(true);

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"uniq_users_username\""));
    }

    @Test
    void testGenerateSql_WithSpecialCharactersInNames() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx-users-email");
        change.setTableName("user-table");
        change.setColumns(List.of("email-address"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"idx-users-email\""));
        assertTrue(sql.contains("\"user-table\""));
        assertTrue(sql.contains("\"email-address\""));
    }

    @Test
    void testGenerateSql_CompleteExample() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_active_email");
        change.setSchemaName("public");
        change.setTableName("users");
        change.setColumns(List.of("is_active", "email"));
        change.setUnique(false);

        // When
        String sql = executor.generateSql(change);

        // Then
        assertNotNull(sql);
        assertTrue(sql.contains("CREATE INDEX"));
        assertFalse(sql.contains("UNIQUE"));
        assertTrue(sql.contains("\"idx_users_active_email\""));
        assertTrue(sql.contains("\"public\".\"users\""));
        assertTrue(sql.contains("\"is_active\", \"email\""));
    }

    @Test
    void testExecute_CapturesCorrectSql() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        executor.execute(change);

        // Then
        verify(jdbcTemplate).execute(sqlCaptor.capture());
        String capturedSql = sqlCaptor.getValue();
        assertTrue(capturedSql.contains("CREATE INDEX"));
        assertTrue(capturedSql.contains("\"idx_users_email\""));
        assertTrue(capturedSql.contains("\"users\""));
        assertTrue(capturedSql.contains("\"email\""));
    }

    @Test
    void testGenerateSql_WithBlankIndexName_AutoGenerates() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("   ");
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"idx_users_email\""));
    }

    @Test
    void testGenerateSql_UniqueFalse_DoesNotIncludeUnique() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));
        change.setUnique(false);

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("CREATE INDEX"));
        assertFalse(sql.contains("UNIQUE"));
    }

    @Test
    void testGenerateSql_UniqueNull_DoesNotIncludeUnique() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));
        change.setUnique(null);

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("CREATE INDEX"));
        assertFalse(sql.contains("UNIQUE"));
    }

    @Test
    void testGenerateSql_ThreeColumns() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_orders_composite");
        change.setTableName("orders");
        change.setColumns(List.of("user_id", "status", "created_at"));

        // When
        String sql = executor.generateSql(change);

        // Then
        assertTrue(sql.contains("\"user_id\", \"status\", \"created_at\""));
    }

    @Test
    void testGenerateSql_Format() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("idx_users_email");
        change.setTableName("users");
        change.setColumns(List.of("email"));

        // When
        String sql = executor.generateSql(change);

        // Then
        // Verify the complete format
        String expected = "CREATE INDEX \"idx_users_email\" ON \"users\" (\"email\")";
        assertEquals(expected, sql);
    }

    @Test
    void testGenerateSql_UniqueFormat() {
        // Given
        CreateIndexChange change = new CreateIndexChange();
        change.setIndexName("uniq_users_username");
        change.setTableName("users");
        change.setColumns(List.of("username"));
        change.setUnique(true);

        // When
        String sql = executor.generateSql(change);

        // Then
        String expected = "CREATE UNIQUE INDEX \"uniq_users_username\" ON \"users\" (\"username\")";
        assertEquals(expected, sql);
    }
}
