-- DataDrift Tracking Tables
-- These tables are used internally by DataDrift to track migration execution

-- Table to track all executed changesets
CREATE TABLE IF NOT EXISTS DATABASECHANGELOG (
    ID VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    FILENAME VARCHAR(255) NOT NULL,
    DATEEXECUTED TIMESTAMP NOT NULL,
    ORDEREXECUTED INTEGER NOT NULL,
    EXECTYPE VARCHAR(10) NOT NULL,
    MD5SUM VARCHAR(35),
    DESCRIPTION VARCHAR(255),
    COMMENTS VARCHAR(255),
    TAG VARCHAR(255),
    LIQUIBASE VARCHAR(20),
    CONTEXTS VARCHAR(255),
    LABELS VARCHAR(255),
    DEPLOYMENT_ID VARCHAR(10),
    CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY (ID, AUTHOR, FILENAME)
);

-- Table to prevent concurrent migrations
CREATE TABLE IF NOT EXISTS DATABASECHANGELOGLOCK (
    ID INTEGER NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    LOCKGRANTED TIMESTAMP,
    LOCKEDBY VARCHAR(255),
    CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID)
);

-- Initialize the lock table with a single row
INSERT INTO DATABASECHANGELOGLOCK (ID, LOCKED)
VALUES (1, FALSE)
ON CONFLICT (ID) DO NOTHING;

-- Create index for faster lookup of executed changesets
CREATE INDEX IF NOT EXISTS IDX_DATABASECHANGELOG_ORDEREXECUTED
ON DATABASECHANGELOG(ORDEREXECUTED);

CREATE INDEX IF NOT EXISTS IDX_DATABASECHANGELOG_DATEEXECUTED
ON DATABASECHANGELOG(DATEEXECUTED);
